http_interactions:
- request:
    method: PATCH
    uri: https://nettskjema.no/api/v3/form/123823/settings
  response:
    status: 204
    headers:
      server: nginx
      date: Wed, 02 Jul 2025 19:56:26 GMT
      set-cookie: JSESSIONID=FAAA79DE6141D2F2EFFCCF5212977FAA; Path=/api/v3; Secure;
        HttpOnly; SameSite=Lax
      strict-transport-security: max-age=31536000 ; includeSubDomains ; preload
      x-application-gateway-proxy: api-own-auth
      x-robots-tag: noindex, nofollow, noarchive
      cache-control: private, max-age=0, no-cache, no-store
  recorded_at: 2025-07-02 19:56:26
recorded_with: VCR-vcr/1.7.0.91, webmockr/2.1.0
